# Generated by Django 5.0.2 on 2024-02-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialpost', '0004_posts_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='file',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='postsimage/'),
        ),
    ]
